image: docker:20.10.17
services:
  - docker:20.10.17-dind

variables:
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - push
  - deploy

#TODO: LOCAL build-nginx / build / test / push-local
include:
  - local: '.gitlab-ci-dev.yml'
  - local: '.gitlab-ci-main.yml'
